// mission.sqm - 00:49:18 01/30/18, generated in 0.33 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

version = 53;

class EditorData {
	moveGridStep = 1.0;
	angleGridStep = 0.261799;
	scaleGridStep = 1.0;
	autoGroupingDist = 10.0;
	toggles = 1;
	
	class ItemIDProvider {
		nextID = 388;
	};
	
	class MarkerIDProvider {
		nextID = 15;
	};
	
	class Camera {
		pos[] = {5183.61, 606.127, 7918.63};
		dir[] = {0.115228, -0.752365, 0.648654};
		up[] = {0.131591, 0.658737, 0.740769};
		aside[] = {0.984624, -5.4657e-007, -0.174908};
	};
};
addons[] = {"exile_client", "A3_Ui_F"};

class AddonsMetaData {
	class List {
		items = 2;
		
		class Item0 {
			className = "exile_client";
			name = "exile_client";
		};
		
		class Item1 {
			className = "A3_Ui_F";
			name = "Arma 3 - User Interface";
			author = "Bohemia Interactive";
			url = "https://www.arma3.com";
		};
	};
};
randomSeed = 2218544;

class ScenarioData {
	author = "Exile Mod";
};

class Mission {
	class Intel {
		timeOfChanges = 2100;
		startWeather = 0.0;
		startWind = 0.0;
		forecastWeather = 0.0;
		forecastWind = 0.0;
		forecastWaves = 0.0;
		year = 1944;
		month = 6;
		day = 6;
		minute = 0;
		startFogDecay = 0.0;
		forecastFogDecay = 0.0;
	};
	
	class Entities {
		items = 99;
		
		class Item0 {
			dataType = "Group";
			side = "Independent";
			
			class Entities {
				items = 100;
				
				class Item0 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7054.38, 301.185, 7819.4};
					};
					side = "Independent";
					flags = 7;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 1;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000183105;
				};
				
				class Item1 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7059.82, 301.232, 7819.32};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 2;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000183105;
				};
				
				class Item2 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7064.01, 301.253, 7819.16};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 3;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000152588;
				};
				
				class Item3 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7068.13, 301.243, 7819.16};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 4;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000274658;
				};
				
				class Item4 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7072.17, 301.269, 7819.32};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 5;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 6.10352e-005;
				};
				
				class Item5 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7076.13, 301.243, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 6;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.00012207;
				};
				
				class Item6 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7079.94, 301.228, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 7;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 9.15527e-005;
				};
				
				class Item7 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7079.86, 301.091, 7816.76};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 8;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 9.15527e-005;
				};
				
				class Item8 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7076.29, 301.116, 7816.76};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 9;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.00012207;
				};
				
				class Item9 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7072.01, 301.159, 7816.99};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 10;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000396729;
				};
				
				class Item10 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7067.9, 301.166, 7816.99};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 11;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000152588;
				};
				
				class Item11 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7064.01, 301.177, 7817.07};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 12;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000579834;
				};
				
				class Item12 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7059.58, 301.15, 7816.99};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 13;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000183105;
				};
				
				class Item13 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7054.22, 301.488, 7816.76};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 14;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.396606;
				};
				
				class Item14 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7053.99, 301.941, 7813.8};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 15;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.973328;
				};
				
				class Item15 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7059.58, 301.027, 7814.04};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 16;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000366211;
				};
				
				class Item16 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7064.01, 301.059, 7814.19};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 17;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000152588;
				};
				
				class Item17 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7067.97, 301.018, 7813.8};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 18;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000732422;
				};
				
				class Item18 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7072.17, 301.01, 7814.04};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 19;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.05176e-005;
				};
				
				class Item19 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7076.21, 300.936, 7813.73};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 20;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000518799;
				};
				
				class Item20 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7079.78, 300.868, 7813.26};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 21;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000549316;
				};
				
				class Item21 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7053.76, 302.341, 7811.24};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 22;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.50238;
				};
				
				class Item22 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7059.66, 301.047, 7811.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 23;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.155579;
				};
				
				class Item23 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7063.85, 300.914, 7811.55};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 24;
					type = "Exile_Unit_GhostPlayer";
				};
				
				class Item24 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7067.97, 300.864, 7811.24};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 25;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000457764;
				};
				
				class Item25 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7071.93, 300.845, 7811.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 26;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000762939;
				};
				
				class Item26 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7075.97, 300.754, 7811.24};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 27;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -3.05176e-005;
				};
				
				class Item27 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7079.63, 300.692, 7810.93};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 28;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000152588;
				};
				
				class Item28 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7053.68, 302.705, 7808.29};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 29;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.01285;
				};
				
				class Item29 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7059.74, 301.371, 7808.6};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 30;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.617706;
				};
				
				class Item30 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7063.78, 300.757, 7808.68};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 31;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000244141;
				};
				
				class Item31 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7068.21, 300.708, 7808.44};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 32;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000671387;
				};
				
				class Item32 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7072.17, 300.684, 7808.83};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 33;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000518799;
				};
				
				class Item33 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7076.29, 300.572, 7808.44};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 34;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000640869;
				};
				
				class Item34 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7079.86, 300.524, 7808.75};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 35;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.05176e-005;
				};
				
				class Item35 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7077.99, 301.236, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 36;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000305176;
				};
				
				class Item36 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7078.07, 301.099, 7816.76};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 37;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000244141;
				};
				
				class Item37 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7077.99, 300.902, 7813.49};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 38;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000305176;
				};
				
				class Item38 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7077.76, 300.715, 7811.01};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 39;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000366211;
				};
				
				class Item39 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7078.23, 300.542, 7808.68};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 40;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000427246;
				};
				
				class Item40 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7074.03, 300.642, 7808.75};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 41;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.05176e-005;
				};
				
				class Item41 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7074.19, 300.799, 7811.32};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 42;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000366211;
				};
				
				class Item42 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7074.27, 300.99, 7814.19};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 43;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000396729;
				};
				
				class Item43 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7074.03, 301.14, 7816.83};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 44;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000244141;
				};
				
				class Item44 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7074.27, 301.258, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 45;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.05176e-005;
				};
				
				class Item45 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7070.3, 301.263, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 46;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000274658;
				};
				
				class Item46 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7070.07, 301.154, 7816.99};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 47;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000274658;
				};
				
				class Item47 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7069.84, 301.022, 7814.04};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 48;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000396729;
				};
				
				class Item48 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7070.07, 300.846, 7811.24};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 49;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000366211;
				};
				
				class Item49 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7070.15, 300.694, 7808.68};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 50;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000579834;
				};
				
				class Item50 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7065.8, 300.757, 7808.75};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 51;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000610352;
				};
				
				class Item51 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7065.8, 300.905, 7811.47};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 52;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.00012207;
				};
				
				class Item52 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7065.88, 301.049, 7814.12};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 53;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.00012207;
				};
				
				class Item53 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7065.8, 301.177, 7816.99};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 54;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -3.05176e-005;
				};
				
				class Item54 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7065.8, 301.255, 7819.16};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 55;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000152588;
				};
				
				class Item55 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7061.91, 301.242, 7819.24};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 56;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000274658;
				};
				
				class Item56 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7061.91, 301.157, 7816.83};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 57;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000335693;
				};
				
				class Item57 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7061.83, 301.052, 7814.27};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 58;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 9.15527e-005;
				};
				
				class Item58 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7061.91, 300.912, 7811.71};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 59;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000396729;
				};
				
				class Item59 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7061.91, 300.89, 7808.75};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 60;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.129364;
				};
				
				class Item60 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7057.87, 301.737, 7808.83};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 61;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.972382;
				};
				
				class Item61 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7057.64, 301.45, 7811.47};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 62;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.555115;
				};
				
				class Item62 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7057.64, 301.033, 7814.27};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 63;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -3.05176e-005;
				};
				
				class Item63 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7057.72, 301.143, 7817.07};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 64;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000335693;
				};
				
				class Item64 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7057.87, 301.235, 7819.71};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 65;
					type = "Exile_Unit_GhostPlayer";
				};
				
				class Item65 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7056.09, 301.205, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 66;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.000366211;
				};
				
				class Item66 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7055.85, 301.114, 7816.83};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 67;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000640869;
				};
				
				class Item67 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7055.62, 301.477, 7814.04};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 68;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.477875;
				};
				
				class Item68 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7055.54, 301.98, 7810.93};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 69;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.13528;
				};
				
				class Item69 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7055.54, 302.294, 7808.37};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 70;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.57562;
				};
				
				class Item70 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7052.51, 301.694, 7819.48};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 71;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.52887;
				};
				
				class Item71 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7052.28, 301.99, 7816.76};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 72;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.921875;
				};
				
				class Item72 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7052.12, 302.313, 7814.04};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 73;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.35587;
				};
				
				class Item73 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7051.89, 302.659, 7811.71};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 74;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.81961;
				};
				
				class Item74 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7051.58, 303.067, 7808.68};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 75;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.3808;
				};
				
				class Item75 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7049.72, 303.439, 7808.44};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 76;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.78995;
				};
				
				class Item76 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7049.79, 303.04, 7811.78};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 77;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.22461;
				};
				
				class Item77 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7049.87, 302.757, 7814.19};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 78;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.82089;
				};
				
				class Item78 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7050.03, 302.512, 7816.52};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 79;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.47922;
				};
				
				class Item79 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7050.18, 302.264, 7819.63};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 80;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.12161;
				};
				
				class Item80 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7048.63, 302.627, 7819.86};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 81;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.50256;
				};
				
				class Item81 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7048.47, 302.814, 7816.76};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 82;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.79977;
				};
				
				class Item82 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7048.39, 302.962, 7814.66};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 83;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.03625;
				};
				
				class Item83 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7048.08, 303.312, 7811.94};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 84;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.52747;
				};
				
				class Item84 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7047.93, 303.702, 7808.68};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 85;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.08295;
				};
				
				class Item85 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7045.83, 304.035, 7808.68};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 86;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.46637;
				};
				
				class Item86 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7045.99, 303.67, 7811.71};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 87;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.94421;
				};
				
				class Item87 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7045.99, 303.344, 7814.97};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 88;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.45731;
				};
				
				class Item88 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7046.22, 303.224, 7816.83};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 89;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.25699;
				};
				
				class Item89 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7046.53, 303.067, 7819.94};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 90;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 1.97617;
				};
				
				class Item90 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7043.66, 304.298, 7808.52};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 91;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.78955;
				};
				
				class Item91 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7043.89, 303.944, 7811.55};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 92;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.27649;
				};
				
				class Item92 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7043.66, 303.641, 7814.97};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 93;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.80713;
				};
				
				class Item93 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7044.2, 303.493, 7816.91};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 94;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.56863;
				};
				
				class Item94 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7044.12, 303.573, 7820.1};
					};
					side = "Independent";
					flags = 1;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 95;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 2.5228;
				};
				
				class Item95 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7082.03, 301.19, 7819.4};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 96;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000244141;
				};
				
				class Item96 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7082.19, 301.053, 7816.83};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 97;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = -0.00012207;
				};
				
				class Item97 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7081.96, 300.805, 7813.26};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 98;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.05176e-005;
				};
				
				class Item98 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7081.96, 300.632, 7811.01};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 99;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 0.000244141;
				};
				
				class Item99 {
					dataType = "Object";
					
					class PositionInfo {
						position[] = {7081.88, 300.439, 7808.44};
					};
					side = "Independent";
					flags = 5;
					
					class Attributes {
						isPlayer = 1;
					};
					id = 100;
					type = "Exile_Unit_GhostPlayer";
					atlOffset = 3.05176e-005;
				};
			};
			
			class Attributes {};
			id = 0;
			atlOffset = 0.000183105;
		};
		
		class Item1 {
			dataType = "Marker";
			position[] = {3380.72, 0.0, 4928.52};
			name = "ExileMarker3";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 103;
			atlOffset = -240.989;
		};
		
		class Item2 {
			dataType = "Marker";
			position[] = {11461.7, 6.18469e+009, 7495.46};
			name = "ExileMarker5";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 100.0;
			b = 100.0;
			drawBorder = 1;
			id = 105;
			atlOffset = 6.18469e+009;
		};
		
		class Item3 {
			dataType = "Marker";
			position[] = {4777.84, 0.0, 2520.45};
			name = "ExileMarker7";
			text = "Boat Trader";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 700.0;
			b = 700.0;
			drawBorder = 1;
			id = 107;
			atlOffset = -9.0;
		};
		
		class Item4 {
			dataType = "Marker";
			position[] = {6737.54, 5.22791e+019, 2471.44};
			name = "ExileMarker9";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 700.0;
			b = 700.0;
			drawBorder = 1;
			id = 109;
			atlOffset = 5.22791e+019;
			
			class CustomAttributes {
				class Attribute0 {
					property = "ExileMarkerZone";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {BOOL};
							};
							value = 1;
						};
					};
				};
				
				class Attribute1 {
					property = "ExileMarkerIcon";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {BOOL};
							};
							value = 1;
						};
					};
				};
				nAttributes = 2;
			};
		};
		
		class Item5 {
			dataType = "Marker";
			position[] = {3081.75, 4.79379e+019, 7909.0};
			name = "ExileMarker11";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 111;
			atlOffset = 4.79379e+019;
		};
		
		class Item6 {
			dataType = "Marker";
			position[] = {2757.44, 1.81152e+014, 9940.34};
			name = "ExileMarker21";
			text = "Lopatino";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 121;
			atlOffset = 1.81152e+014;
		};
		
		class Item7 {
			dataType = "Marker";
			position[] = {2758.47, 105.076, 9939.09};
			name = "ExileMarker22";
			type = "ExileSpawnZoneIcon";
			id = 122;
			atlOffset = -168.916;
		};
		
		class Item8 {
			dataType = "Marker";
			position[] = {11996.8, 1.35246e+015, 3531.36};
			name = "ExileMarker23";
			text = "Kamyshovo";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 123;
			atlOffset = 1.35246e+015;
		};
		
		class Item9 {
			dataType = "Marker";
			position[] = {11996.8, 6.12508, 3531.47};
			name = "ExileMarker24";
			type = "ExileSpawnZoneIcon";
			id = 124;
			atlOffset = -2.28882e-005;
		};
		
		class Item10 {
			dataType = "Marker";
			position[] = {12165.9, 0.0, 9314.54};
			name = "ExileMarker25";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 700.0;
			b = 700.0;
			drawBorder = 1;
			id = 125;
			atlOffset = -32.141;
		};
		
		class Item11 {
			dataType = "Marker";
			position[] = {12026.5, 4.79379e+019, 12623.9};
			name = "ExileMarker27";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 600.0;
			b = 600.0;
			drawBorder = 1;
			id = 127;
			atlOffset = 4.79379e+019;
		};
		
		class Item12 {
			dataType = "Marker";
			position[] = {13392.1, 0.0, 6216.15};
			name = "ExileMarker31";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileConcreteMixerZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 350.0;
			b = 350.0;
			drawBorder = 1;
			id = 131;
			atlOffset = -5.38672;
		};
		
		class Item13 {
			dataType = "Marker";
			position[] = {13001.2, 0.0, 10031.6};
			name = "ExileMarker33";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileConcreteMixerZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 500.0;
			b = 500.0;
			drawBorder = 1;
			id = 133;
			atlOffset = -6.0;
		};
		
		class Item14 {
			dataType = "Marker";
			position[] = {13082.1, 5.22436e+019, 6985.0};
			name = "ExileMarker37";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 350.0;
			b = 350.0;
			drawBorder = 1;
			id = 137;
			atlOffset = 5.22436e+019;
		};
		
		class Item15 {
			dataType = "Marker";
			position[] = {12178.7, 5.22791e+019, 7288.02};
			name = "ExileMarker39";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 139;
			atlOffset = 5.22791e+019;
		};
		
		class Item16 {
			dataType = "Marker";
			position[] = {3940.91, 4.79379e+019, 8943.7};
			name = "ExileMarker40";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 140;
			atlOffset = 4.79379e+019;
			
			class CustomAttributes {
				class Attribute0 {
					property = "ExileMarkerZone";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {STRING};
							};
							value = "";
						};
					};
				};
				
				class Attribute1 {
					property = "ExileMarkerIcon";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {STRING};
							};
							value = "";
						};
					};
				};
				nAttributes = 2;
			};
		};
		
		class Item17 {
			dataType = "Marker";
			position[] = {10123.2, -2.78797e-023, 5519.26};
			name = "ExileMarker43";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 143;
			atlOffset = -244.997;
		};
		
		class Item18 {
			dataType = "Marker";
			position[] = {4596.82, 0.0, 10065.9};
			name = "ExileMarker45";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 1000.0;
			b = 1000.0;
			drawBorder = 1;
			id = 145;
			atlOffset = -339.0;
			
			class CustomAttributes {
				class Attribute0 {
					property = "ExileMarkerZone";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {STRING};
							};
							value = "";
						};
					};
				};
				
				class Attribute1 {
					property = "ExileMarkerIcon";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {STRING};
							};
							value = "";
						};
					};
				};
				nAttributes = 2;
			};
		};
		
		class Item19 {
			dataType = "Marker";
			position[] = {11066.2, 4.79379e+019, 12318.8};
			name = "ExileMarker47";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 147;
			atlOffset = 4.79379e+019;
		};
		
		class Item20 {
			dataType = "Marker";
			position[] = {3664.19, 9.47958e+033, 2466.07};
			name = "ExileMarker48";
			text = "Komarovo";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 148;
			atlOffset = 9.47958e+033;
		};
		
		class Item21 {
			dataType = "Marker";
			position[] = {3661.61, 6.88491, 2468.11};
			name = "ExileMarker49";
			type = "ExileSpawnZoneIcon";
			id = 149;
			atlOffset = 1.81198e-005;
		};
		
		class Item22 {
			dataType = "Marker";
			position[] = {13361.8, 0.0, 12880.8};
			name = "ExileMarker50";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 150;
			atlOffset = -93.9712;
		};
		
		class Item23 {
			dataType = "Marker";
			position[] = {10220.9, 5.22436e+019, 2163.57};
			name = "ExileMarker54";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 700.0;
			b = 700.0;
			drawBorder = 1;
			id = 154;
			atlOffset = 5.22436e+019;
		};
		
		class Item24 {
			dataType = "Marker";
			position[] = {12319.0, 4.79379e+019, 10780.2};
			name = "ExileMarker56";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 156;
			atlOffset = 4.79379e+019;
		};
		
		class Item25 {
			dataType = "Marker";
			position[] = {4439.82, 4.51648e-013, 4609.97};
			name = "ExileMarker3_1";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 116;
			atlOffset = -231.982;
		};
		
		class Item26 {
			dataType = "Marker";
			position[] = {5880.81, 5.22436e+019, 4724.54};
			name = "ExileMarker3_2";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 117;
			atlOffset = 5.22436e+019;
		};
		
		class Item27 {
			dataType = "Marker";
			position[] = {3343.76, 5.22791e+019, 3930.37};
			name = "ExileMarker3_3";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 118;
			atlOffset = 5.22791e+019;
		};
		
		class Item28 {
			dataType = "Marker";
			position[] = {1913.5, 9.47708e+033, 2220.65};
			name = "ExileMarker3_4";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 119;
			atlOffset = 9.47708e+033;
		};
		
		class Item29 {
			dataType = "Marker";
			position[] = {7589.18, 5.22436e+019, 5122.25};
			name = "ExileMarker3_5";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 120;
			atlOffset = 5.22436e+019;
		};
		
		class Item30 {
			dataType = "Marker";
			position[] = {6520.5, 5.22791e+019, 6125.17};
			name = "ExileMarker3_6";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 121;
			atlOffset = 5.22791e+019;
		};
		
		class Item31 {
			dataType = "Marker";
			position[] = {7093.16, 5.22436e+019, 7675.14};
			name = "ExileMarker3_7";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 122;
			atlOffset = 5.22436e+019;
		};
		
		class Item32 {
			dataType = "Marker";
			position[] = {9155.51, 5.22791e+019, 3918.85};
			name = "ExileMarker3_8";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 123;
			atlOffset = 5.22791e+019;
		};
		
		class Item33 {
			dataType = "Marker";
			position[] = {12766.5, 5.22791e+019, 4430.82};
			name = "ExileMarker3_9";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 124;
			atlOffset = 5.22791e+019;
		};
		
		class Item34 {
			dataType = "Marker";
			position[] = {11337.4, 5.22791e+019, 5460.14};
			name = "ExileMarker3_10";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 125;
			atlOffset = 5.22791e+019;
		};
		
		class Item35 {
			dataType = "Marker";
			position[] = {9642.42, 5.22791e+019, 6558.85};
			name = "ExileMarker3_12";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 127;
			atlOffset = 5.22791e+019;
		};
		
		class Item36 {
			dataType = "Marker";
			position[] = {11219.4, 5.22436e+019, 6587.8};
			name = "ExileMarker3_13";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 128;
			atlOffset = 5.22436e+019;
		};
		
		class Item37 {
			dataType = "Marker";
			position[] = {9658.75, 0.0, 8779.79};
			name = "ExileMarker3_15";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 500.0;
			b = 500.0;
			drawBorder = 1;
			id = 130;
			atlOffset = -293.059;
		};
		
		class Item38 {
			dataType = "Marker";
			position[] = {5980.94, 0.0, 10275.8};
			name = "ExileMarker3_17";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 132;
			atlOffset = -270.432;
		};
		
		class Item39 {
			dataType = "Marker";
			position[] = {2007.16, 4.79379e+019, 7353.23};
			name = "ExileMarker3_19";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 134;
			atlOffset = 4.79379e+019;
		};
		
		class Item40 {
			dataType = "Marker";
			position[] = {2543.98, 5.22791e+019, 6360.26};
			name = "ExileMarker3_20";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 135;
			atlOffset = 5.22791e+019;
		};
		
		class Item41 {
			dataType = "Marker";
			position[] = {4505.1, 5.22436e+019, 6434.73};
			name = "ExileMarker3_21";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 136;
			atlOffset = 5.22436e+019;
		};
		
		class Item42 {
			dataType = "Marker";
			position[] = {4790.58, 5.22791e+019, 6816.41};
			name = "ExileMarker3_22";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 137;
			atlOffset = 5.22791e+019;
		};
		
		class Item43 {
			dataType = "Marker";
			position[] = {4951.94, 5.22791e+019, 5618.64};
			name = "ExileMarker3_23";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 138;
			atlOffset = 5.22791e+019;
		};
		
		class Item44 {
			dataType = "Marker";
			position[] = {1705.07, 5.22436e+019, 3833.36};
			name = "ExileMarker3_24";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 139;
			atlOffset = 5.22436e+019;
		};
		
		class Item45 {
			dataType = "Marker";
			position[] = {5340.76, 4.79379e+019, 8602.93};
			name = "ExileMarker3_25";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 200.0;
			b = 200.0;
			drawBorder = 1;
			id = 140;
			atlOffset = 4.79379e+019;
		};
		
		class Item46 {
			dataType = "Marker";
			position[] = {8630.77, -2.68712e-023, 11854.5};
			name = "ExileMarker49_2";
			type = "ExileSpawnZoneIcon";
			id = 117;
			atlOffset = -192.315;
		};
		
		class Item47 {
			dataType = "Marker";
			position[] = {8439.22, 353.701, 6733.36};
			name = "ExileMarker49_3";
			type = "ExileSpawnZoneIcon";
			id = 118;
			atlOffset = -1.07336;
		};
		
		class Item48 {
			dataType = "Marker";
			position[] = {12848.0, 5.31477, 8120.35};
			name = "ExileMarker49_4";
			type = "ExileSpawnZoneIcon";
			id = 119;
			atlOffset = 0.000325203;
		};
		
		class Item49 {
			dataType = "Marker";
			position[] = {5000.19, -1.33304e-034, 12502.9};
			name = "ExileMarker49_5";
			type = "ExileSpawnZoneIcon";
			id = 120;
			atlOffset = -181.997;
		};
		
		class Item50 {
			dataType = "Marker";
			position[] = {5001.06, -5.2098e-011, 12519.0};
			name = "ExileMarker21_2";
			text = "Petrovka";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 122;
			atlOffset = -181.99;
		};
		
		class Item51 {
			dataType = "Marker";
			position[] = {8629.96, -1.16608e-028, 11849.4};
			name = "ExileMarker21_3";
			text = "Gvozdno";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 123;
			atlOffset = -192.505;
		};
		
		class Item52 {
			dataType = "Marker";
			position[] = {12847.9, -5.45454e-035, 8121.94};
			name = "ExileMarker21_4";
			text = "Nizhnoye";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 124;
			atlOffset = -5.29762;
		};
		
		class Item53 {
			dataType = "Marker";
			position[] = {8442.87, -7.58698e-028, 6731.5};
			name = "ExileMarker21_5";
			text = "Guglovo";
			markerType = ELLIPSE;
			type = "ExileSpawnZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 472.33;
			b = 472.33;
			drawBorder = 1;
			id = 125;
			atlOffset = -354.619;
		};
		
		class Item54 {
			dataType = "Marker";
			position[] = {10675.7, -2.89391e-023, 8029.92};
			name = "ExileMarker43_1";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 126;
			atlOffset = -210.99;
		};
		
		class Item55 {
			dataType = "Marker";
			position[] = {3712.48, 0.0, 5981.46};
			name = "ExileMarker3_11";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 720.0;
			b = 720.0;
			drawBorder = 1;
			id = 121;
			atlOffset = -402.0;
		};
		
		class Item56 {
			dataType = "Marker";
			position[] = {10430.5, 0.0, 9699.69};
			name = "ExileMarker3_16";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 121;
			atlOffset = -140.777;
		};
		
		class Item57 {
			dataType = "Marker";
			position[] = {13651.9, 1.00604e+035, 3535.54};
			name = "marker_26";
			markerType = RECTANGLE;
			type = "rectangle";
			colorName = "ColorOrange";
			fillName = "SolidFull";
			a = 5.0;
			b = 610.0;
			angle = 135.0;
			id = 121;
			atlOffset = 1.00604e+035;
		};
		
		class Item58 {
			dataType = "Marker";
			position[] = {14081.8, 1.00604e+035, 3038.45};
			name = "marker_27";
			markerType = RECTANGLE;
			type = "rectangle";
			colorName = "ColorOrange";
			fillName = "SolidFull";
			a = 5.0;
			b = 70.0;
			id = 122;
			atlOffset = 1.00604e+035;
		};
		
		class Item59 {
			dataType = "Marker";
			position[] = {13657.4, 7.45388e+025, 3539.26};
			name = "marker_29";
			text = "Skalisty Bridge";
			type = "c_car";
			id = 123;
			atlOffset = 7.45388e+025;
		};
		
		class Item60 {
			dataType = "Marker";
			position[] = {13235.3, 0.0, 3949.06};
			name = "ExileMarker9_2";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 150.0;
			b = 150.0;
			drawBorder = 1;
			id = 124;
			atlOffset = -5.18541;
		};
		
		class Item61 {
			dataType = "Marker";
			position[] = {5484.65, 0.0, 2145.35};
			name = "ExileMarker7_1";
			text = "Boat Trader";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 317;
			atlOffset = -19.3466;
		};
		
		class Item62 {
			dataType = "Marker";
			position[] = {13607.0, 0.0, 2972.42};
			name = "ExileMarker9_3";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 800.0;
			b = 800.0;
			drawBorder = 1;
			id = 319;
			atlOffset = -36.6078;
		};
		
		class Item63 {
			dataType = "Marker";
			position[] = {13559.4, 0.0, 4037.5};
			name = "ExileMarker9_4";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 320;
			atlOffset = -19.0347;
		};
		
		class Item64 {
			dataType = "Marker";
			position[] = {4848.96, 0.0, 9286.8};
			name = "ExileMarker3_18";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 400.0;
			b = 400.0;
			drawBorder = 1;
			id = 323;
			atlOffset = -349.062;
		};
		
		class Item65 {
			dataType = "Marker";
			position[] = {2731.71, 0.0, 5400.63};
			name = "ExileMarker54_1";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 700.0;
			b = 700.0;
			drawBorder = 1;
			id = 324;
			atlOffset = -208.921;
		};
		
		class Item66 {
			dataType = "Marker";
			position[] = {7134.97, -13.4419, 2727.46};
			name = "ExileMarker30";
			type = "ExileConcreteMixerZoneIcon";
			id = 452;
			atlOffset = -19.4319;
		};
		
		class Item67 {
			dataType = "Marker";
			position[] = {13119.7, -13.43, 10432.4};
			name = "ExileMarker30_1";
			type = "ExileConcreteMixerZoneIcon";
			id = 453;
			atlOffset = -19.43;
		};
		
		class Item68 {
			dataType = "Marker";
			position[] = {555.369, -0.00397873, 116.474};
			name = "marker_17";
			markerType = ELLIPSE;
			type = "ellipse";
			colorName = "ColorBlue";
			a = 100.0;
			b = 100.0;
			id = 456;
			atlOffset = 58.0116;
		};
		
		class Item69 {
			dataType = "Marker";
			position[] = {552.433, -2.12752, -182.622};
			name = "marker_18";
			markerType = ELLIPSE;
			type = "ellipse";
			colorName = "ColorRed";
			a = 100.0;
			b = 100.0;
			id = 457;
			atlOffset = 61.3124;
		};
		
		class Item70 {
			dataType = "Marker";
			position[] = {552.433, 16.6239, -488.266};
			name = "marker_19";
			markerType = ELLIPSE;
			type = "ellipse";
			colorName = "ColorYellow";
			a = 100.0;
			b = 100.0;
			id = 458;
			atlOffset = 92.8443;
		};
		
		class Item71 {
			dataType = "Marker";
			position[] = {552.062, 0.0, -488.213};
			name = "marker_20";
			text = "Money Drop";
			type = "mil_dot";
			colorName = "ColorWhite";
			id = 459;
			atlOffset = 76.2099;
		};
		
		class Item72 {
			dataType = "Marker";
			position[] = {551.412, 0.0, -181.975};
			name = "marker_21";
			text = "Weapon Drop";
			type = "mil_dot";
			colorName = "ColorWhite";
			id = 460;
			atlOffset = 63.3902;
		};
		
		class Item73 {
			dataType = "Marker";
			position[] = {556.471, 0.0, 117.718};
			name = "marker_22";
			text = "IKEA Drop";
			type = "mil_dot";
			colorName = "ColorWhite";
			id = 461;
			atlOffset = 58.0072;
		};
		
		class Item74 {
			dataType = "Marker";
			position[] = {951.296, -4.70734, -387.547};
			name = "marker_23";
			type = "o_unknown";
			id = 462;
			atlOffset = 78.5919;
		};
		
		class Item75 {
			dataType = "Marker";
			position[] = {946.266, -10.5675, -188.828};
			name = "marker_24";
			type = "o_unknown";
			colorName = "ColorBlack";
			id = 463;
			atlOffset = 64.3577;
		};
		
		class Item76 {
			dataType = "Marker";
			position[] = {946.756, -1.10946, 9.39911};
			name = "marker_25";
			type = "o_unknown";
			colorName = "ColorBlue";
			id = 464;
			atlOffset = 62.6635;
		};
		
		class Item77 {
			dataType = "Marker";
			position[] = {946.279, 0.0, -188.781};
			name = "marker_28";
			text = "SWAT (MEDIUM)";
			type = "mil_dot";
			colorName = "ColorWhite";
			id = 465;
			atlOffset = 74.9213;
		};
		
		class Item78 {
			dataType = "Marker";
			position[] = {951.289, 0.0, -387.544};
			name = "marker_30";
			text = "Military (HARD)";
			type = "mil_dot";
			colorName = "ColorWhite";
			id = 466;
			atlOffset = 83.2989;
		};
		
		class Item79 {
			dataType = "Marker";
			position[] = {946.755, 0.0, 9.402};
			name = "marker_31";
			text = "Cops (EASY)";
			type = "mil_dot";
			colorName = "ColorWhite";
			id = 467;
			atlOffset = 63.7729;
		};
		
		class Item80 {
			dataType = "Marker";
			position[] = {2601.38, -12.0269, 1921.32};
			name = "ExileMarker53";
			type = "ExileBoatTraderIcon";
			id = 469;
			atlOffset = -12.952;
		};
		
		class Item81 {
			dataType = "Marker";
			position[] = {12821, 0.0, 3603.8};
			name = "ExileMarker53_1";
			type = "ExileBoatTraderIcon";
			id = 470;
			atlOffset = 0.201912;
		};
		
		class Item82 {
			dataType = "Marker";
			position[] = {12917.0, -10.5723, 8973.32};
			name = "ExileMarker53_2";
			type = "ExileBoatTraderIcon";
			id = 471;
			atlOffset = -13.0356;
		};
		
		class Item83 {
			dataType = "Marker";
			position[] = {2600.75, 0.0, 1923.61};
			name = "ExileMarker25_3";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 150.0;
			b = 150.0;
			drawBorder = 1;
			id = 475;
			atlOffset = -1.26841;
		};
		
		class Item84 {
			dataType = "Marker";
			position[] = {12891, 4.79379e+019, 12716.5};
			name = "ExileMarker27_1";
			text = "Non-Construction Zone";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 291;
			atlOffset = 4.79379e+019;
		};
		
		class Item85 {
			dataType = "Marker";
			position[] = {6327.78, 181.506, 7803.53};
			name = "ExileMarker52_1";
			type = "ExileTraderZoneIcon";
			id = 374;
			atlOffset = -123.49;
		};
		
		class Item86 {
			dataType = "Marker";
			position[] = {6327.78, 181.506, 7803.53};
			name = "ExileMarker51_1";
			markerType = ELLIPSE;
			type = "ExileTraderZone";
			colorName = "ColorBlack";
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 375;
			atlOffset = -123.489;
		};
		
		class Item87 {
			dataType = "Marker";
			position[] = {1907.3, 268.651, 12448.4};
			name = "ExileMarker52";
			type = "ExileTraderZoneIcon";
			id = 376;
			atlOffset = 25.6579;
		};
		
		class Item88 {
			dataType = "Marker";
			position[] = {1907.3, 145.224, 12448.4};
			name = "ExileMarker51";
			markerType = ELLIPSE;
			type = "ExileTraderZone";
			colorName = "ColorBlack";
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 377;
			atlOffset = -97.7686;
		};
		
		class Item89 {
			dataType = "Marker";
			position[] = {11444.6, 193.788, 11354.9};
			name = "ExileMarker52_2";
			type = "ExileTraderZoneIcon";
			id = 378;
			atlOffset = -123.487;
		};
		
		class Item90 {
			dataType = "Marker";
			position[] = {11444.6, 193.788, 11354.9};
			name = "ExileMarker51_2";
			markerType = ELLIPSE;
			type = "ExileTraderZone";
			colorName = "ColorBlack";
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 379;
			atlOffset = -123.487;
		};
		
		class Item91 {
			dataType = "Marker";
			position[] = {8053.32, 5.77199, 3356.33};
			name = "ExileMarker52_3";
			type = "ExileTraderZoneIcon";
			id = 380;
			atlOffset = -4.76837e-007;
		};
		
		class Item92 {
			dataType = "Marker";
			position[] = {8053.32, -117.506, 3356.33};
			name = "ExileMarker51_3";
			markerType = ELLIPSE;
			type = "ExileTraderZone";
			colorName = "ColorBlack";
			fillName = "Border";
			a = 300.0;
			b = 300.0;
			drawBorder = 1;
			id = 381;
			atlOffset = -123.278;
		};
		
		class Item93 {
			dataType = "Marker";
			position[] = {5226.47, 2.09668, 2246};
			name = "ExileMarker28";
			type = "ExileAircraftTraderIcon";
			id = 382;
			atlOffset = -6.95667;
		};
		
		class Item94 {
			dataType = "Marker";
			position[] = {5059.73, 332.057, 9725.51};
			name = "ExileMarker28_1";
			type = "ExileAircraftTraderIcon";
			id = 383;
			atlOffset = -6.952;
		};
		
		class Item95 {
			dataType = "Marker";
			position[] = {12520.4, 151.95, 12595.6};
			name = "ExileMarker28_2";
			type = "ExileAircraftTraderIcon";
			id = 384;
			atlOffset = -6.95;
		};
		
		class Item96 {
			dataType = "Marker";
			position[] = {9700.62, 70.125, 8878.7};
			name = "ExileMarker26";
			type = "ExileSpecOpsTraderIcon";
			id = 385;
			atlOffset = -228.875;
		};
		
		class Item97 {
			dataType = "Marker";
			position[] = {10179.8, -222.875, 1814.86};
			name = "ExileMarker26_1";
			type = "ExileSpecOpsTraderIcon";
			id = 386;
			atlOffset = -228.875;
		};
		
		class Item98 {
			dataType = "Marker";
			position[] = {4066.35, 5.094, 11367.5};
			name = "ExileMarker45_1";
			markerType = ELLIPSE;
			type = "ExileNonConstructionZone";
			colorName = "ColorBlack";
			alpha = 0.0;
			fillName = "Border";
			a = 600.0;
			b = 600.0;
			drawBorder = 1;
			id = 387;
			atlOffset = -344.254;
			
			class CustomAttributes {
				class Attribute0 {
					property = "ExileMarkerZone";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {STRING};
							};
							value = "";
						};
					};
				};
				
				class Attribute1 {
					property = "ExileMarkerIcon";
					expression = "false";
					
					class Value {
						class data {
							class type {
								type[] = {STRING};
							};
							value = "";
						};
					};
				};
				nAttributes = 2;
			};
		};
	};
};
